mybatis:
  type-aliases-package: cn.ultronxr.gameregister.bean.mybatis.bean
  mapper-locations: classpath:mapper/*.xml




#    # 以下内容由 Nacos 配置中心配置分发
#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    druid:
#      name: game-register-service-druid
#      url:
#      username:
#      password:
#      filters: stat,wall
#      initialSize: 5
#      maxActive: 20
#      maxWait: 60000
#      minIdle: 5
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: select 1 from dual
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxOpenPreparedStatements: 20
#
#server:
#  port: 8111
#  servlet:
#    context-path: /xx
